apiVersion: apps/v1
kind: Deployment
metadata:
 name: sample
 labels:
  app: sample
spec:
 replicas: 2
 selector:
  matchLabels:
   app: sample
  spec:
   containers:
    - name: webserver
      image: nextgen98/sample
      ports:
       - containerPort: 8000