apiVersion: v1
kind: Service
metadata:
 name: sample
 labels:
  app: sample
spec:
 ports:
 - name: port8080
   port: 8080
 selector:
   app: sample
   tier: sample
 type: LoadBalancer
---
apiVersion: v1
kind: Deployment
metadata:
 name: sample
 labels:
  app: sample
spec:
 selector:
  matchLabels:
   app: sample
   tier: sample
 strategy: 
  type: Recreate
 template:
  metadata:
   labels:
    app: sample
    tier: sample 
  spec:
   containers:
   -image: nextgen98/sample
    name: sample
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      name: port8080